# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_user',
            new_name='user',
        ),
    ]
