# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190424_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_shop',
            new_name='shop',
        ),
    ]
