# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-24 11:41
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190424_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='任务描述'),
        ),
    ]
