# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-15 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '地址', 'verbose_name_plural': '地址'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gender',
            new_name='user_gender',
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('1', '普通用户'), ('2', '采购'), ('3', '收购'), ('4', '运输'), ('5', '店铺')], default='1', max_length=10, unique=True, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_creditscore',
            field=models.IntegerField(default=0, verbose_name='会员的重要程度/经验值'),
        ),
        migrations.AlterModelTable(
            name='address',
            table='fb_address',
        ),
    ]
