# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190415_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='用户电话'),
        ),
    ]
