# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-20 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190417_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_realname',
            new_name='user_ifrealname',
        ),
        migrations.AddField(
            model_name='user',
            name='user_importance',
            field=models.IntegerField(default=0, verbose_name='会员的重要程度/经验值'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_creditscore',
            field=models.IntegerField(default=0, verbose_name='信用积分'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
